In [1]:
import numpy as np


In [2]:
my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1,my_list2]

In [7]:
my_array2 = np.array(my_lists)

In [8]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
my_array2.shape

(2, 4)

In [10]:
my_array2.dtype

dtype('int32')

In [11]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [12]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [13]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [14]:
dtype('float64')

NameError: name 'dtype' is not defined

In [15]:
np.empty(5)
np.empty((3,4))

array([[  1.28950426e-311,   3.16202013e-322,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   1.90319892e+185,   3.69422791e-057,
          1.41525633e-076],
       [  9.51068015e+169,   1.45115066e-047,   1.90188152e-052,
          1.25673905e-071]])

In [16]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
from __future__ import division

In [19]:
arr1 = np.array([[1,2,3],[8,9,10]])

In [20]:
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [21]:
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [22]:
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [24]:
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]], dtype=int32)